#pragma once

#define VERSION L"v0.2.0-alpha"

#define WINDOW_INITIAL_RENDER_WIDTH 854
#define WINDOW_INITIAL_HEIGHT 480
#define UI_WIDTH 200

enum {
	RENDER_MODE_FILLRECT,
	RENDER_MODE_BITMAP_SETPIXEL,
	RENDER_MODE_BITMAP_PIXELARRAY,
};

#define RENDER_MODE RENDER_MODE_BITMAP_PIXELARRAY
