#pragma once

#define VERSION L"v0.2.0-alpha"

constexpr int WINDOW_INITIAL_RENDER_HEIGHT = 480;
constexpr int WINDOW_INITIAL_RENDER_WIDTH = WINDOW_INITIAL_RENDER_HEIGHT * (16.0 / 9.0); // perfect 16:9 conversion, currently 853
constexpr int UI_WIDTH = 200;

enum {
	RENDER_MODE_FILLRECT,
	RENDER_MODE_BITMAP_SETPIXEL,
	RENDER_MODE_BITMAP_PIXELARRAY,
};

constexpr int RENDER_MODE = RENDER_MODE_BITMAP_PIXELARRAY;
